apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demoApp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: demoApp
    spec:
      containers:
        - name: kube-demo-container
          image: hcwxd/blue-whale
          ports:
            - containerPort: 3000
    















 