apiVersion: v1
kind: Service
metadata:
  name: kube-demo-service
  labels:
    app: demoApp
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
      nodePort: 30001
  selector:
    app: demoApp