apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: hello
              image: jobber
              args:
                - /bin/sh
                - -c
                - date; echo Hello
          restartPolicy: OnFailure

  
